import assert from 'node:assert/strict'
import { mkdir, writeFile } from 'node:fs/promises'
import { pathToFileURL } from 'node:url'

const { chromium } = await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE || 'C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs').href)
const output = process.env.COMPONENT_SMOKE_OUTPUT || 'C:/Users/Administrator/Documents/test/outputs/component-ui'
const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_PATH || 'C:/Users/Administrator/AppData/Local/ms-playwright/chromium-1234/chrome-win64/chrome.exe' })
const report = { checks: [], errors: [], screenshots: [] }
await mkdir(output, { recursive: true })
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } })
  await context.addInitScript(() => localStorage.setItem('wechat-dialog-generator:announcement-read', '2026-09-10-account-v1'))
  // Never call real account/analytics/payment endpoints from this regression.
  await context.route('**/*', route => new URL(route.request().url()).origin === 'http://127.0.0.1:4178' ? route.continue() : route.abort())
  const page = await context.newPage()
  page.setDefaultTimeout(8000)
  page.on('pageerror', error => report.errors.push(error.message))
  const active = () => page.locator('.studio-tool-page:not([hidden])')
  const shot = async name => { const path = `${output}/${name}.png`; await page.screenshot({ path }); report.screenshots.push(path) }
  await page.goto('http://127.0.0.1:4178/?tool=batch')
  const mode = active().getByRole('combobox', { name: '默认导出方式' })
  await mode.waitFor()
  const previewBefore = await active().locator('.workspace-preview').boundingBox()
  const trigger = await mode.boundingBox()
  await mode.click()
  const popup = page.locator('[data-slot=select-content]:visible')
  await popup.waitFor()
  const menu = await popup.boundingBox()
  assert.ok(Math.abs(menu.y - trigger.y - trigger.height - 6) < 2, 'menu anchors below trigger with 6px gap')
  assert.deepEqual(await active().locator('.workspace-preview').boundingBox(), previewBefore, 'opening select must not shift layout')
  assert.notEqual(await page.locator('body').evaluate(node => getComputedStyle(node).overflow), 'hidden', 'nonmodal select must not lock page scrolling')
  await shot('batch-select-open')
  await page.keyboard.press('Escape')
  await popup.waitFor({ state: 'hidden' })
  assert.equal(await mode.evaluate(node => node === document.activeElement), true, 'Escape returns select focus')
  await mode.press('ArrowDown')
  await page.getByRole('option', { name: '标准截图（顶部一屏）', exact: true }).click()
  assert.match(await mode.innerText(), /标准截图/)
  await mode.click()
  await active().getByRole('heading', { name: '批量聊天制作', exact: true }).click()
  await popup.waitFor({ state: 'hidden' })
  report.checks.push('Select: real portal, positioning, selection, Escape focus, outside click, no layout shift or scroll lock')

  await page.locator('.studio-tool-nav a[href*="tool=chat"]').click()
  await active().getByRole('button', { name: '加载示例', exact: true }).click()
  await active().getByRole('button', { name: '解析并导入', exact: true }).click()
  const append = active().getByRole('button', { name: '添加消息', exact: true })
  assert.equal(await append.getAttribute('aria-expanded'), 'false')
  await append.click()
  const count = await active().locator('.wc-bubble').count()
  await active().getByPlaceholder('输入消息内容...', { exact: true }).fill('紧凑工作页追加消息测试')
  await active().getByRole('button', { name: '添加', exact: true }).click()
  assert.equal(await active().locator('.wc-bubble').count(), count + 1)
  await append.click()
  report.checks.push('On-demand message editor expands, appends a real local message and collapses without losing content')
  await active().getByRole('tab', { name: '手机样式', exact: true }).click()
  const signal = active().getByRole('combobox', { name: '主卡信号', exact: true })
  await signal.click()
  await page.getByRole('option', { name: '2 格', exact: true }).click()
  assert.equal(await signal.innerText(), '2 格')
  const wifi = active().getByRole('switch', { name: 'Wi-Fi', exact: true })
  const checked = await wifi.getAttribute('aria-checked')
  await wifi.focus(); await page.keyboard.press('Space')
  assert.notEqual(await wifi.getAttribute('aria-checked'), checked)
  const slider = active().getByRole('slider', { name: '电量', exact: true })
  const battery = Number(await slider.getAttribute('aria-valuenow'))
  await slider.focus(); await page.keyboard.press('ArrowRight')
  assert.equal(Number(await slider.getAttribute('aria-valuenow')), Math.min(100, battery + 1))
  const color = active().getByRole('button', { name: '自己气泡色', exact: true })
  await color.click()
  const hex = page.getByRole('textbox', { name: '自己气泡色 HEX 色值', exact: true })
  await hex.fill('invalid'); await hex.press('Enter')
  await page.getByRole('alert').filter({ hasText: '请输入有效的 HEX 色值' }).waitFor()
  await hex.fill('#B8D6FF'); await hex.press('Enter')
  await page.locator('.color-field-popup').waitFor({ state: 'hidden' })
  assert.match(await color.innerText(), /#B8D6FF/)
  await shot('chat-settings')
  report.checks.push('Settings: custom Select, keyboard Switch/Slider, validated color Popover update')

  await active().getByRole('tab', { name: '聊天内容', exact: true }).click()
  await active().getByRole('button', { name: '同款链接', exact: true }).click()
  const dialog = page.getByRole('alertdialog')
  await dialog.waitFor()
  assert.match(await dialog.innerText(), /包含当前对话文字/)
  assert.equal(await dialog.getByRole('button', { name: '取消', exact: true }).evaluate(node => node === document.activeElement), true, 'safe action initially focused')
  await page.keyboard.press('Escape')
  await dialog.waitFor({ state: 'hidden' })
  assert.equal(await active().getByRole('button', { name: '同款链接', exact: true }).evaluate(node => node === document.activeElement), true, 'dialog returns focus to invoker')
  report.checks.push('AlertDialog: safe initial focus, Escape cancel and focus restoration; no share sent')

  await page.setViewportSize({ width: 390, height: 844 })
  await active().getByRole('tab', { name: '手机样式', exact: true }).click()
  await active().getByRole('combobox', { name: '手机时间分钟', exact: true }).click()
  const minutePopup = page.locator('[data-slot=select-content]:visible')
  await minutePopup.waitFor()
  await page.waitForFunction(() => Boolean(document.activeElement?.closest('[data-slot=select-content]')))
  const mobileMenu = await minutePopup.boundingBox()
  assert.ok(mobileMenu.x >= 0 && mobileMenu.x + mobileMenu.width <= 390)
  assert.ok(mobileMenu.y >= 0 && mobileMenu.y + mobileMenu.height <= 844)
  await page.keyboard.press('End')
  await page.getByRole('option', { name: '59', exact: true }).waitFor()
  await page.keyboard.press('Enter')
  await minutePopup.waitFor({ state: 'hidden' })
  assert.equal(await active().getByRole('combobox', { name: '手机时间分钟', exact: true }).innerText(), '59')
  await color.click()
  const mobileColor = await page.locator('.color-field-popup').boundingBox()
  assert.ok(mobileColor.x >= 0 && mobileColor.x + mobileColor.width <= 390)
  await shot('mobile-color-popup')
  await page.keyboard.press('Escape')
  await active().getByRole('button', { name: '预览与导出', exact: true }).click()
  assert.equal(await active().locator('.workspace-preview').isVisible(), true)
  await active().getByRole('button', { name: '编辑内容', exact: true }).click()
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
  const nativeControls = await page.locator('select:visible, input[type=range]:visible, input[type=checkbox]:visible, input[type=color]:visible, input[type=time]:visible, details:visible').evaluateAll(nodes => nodes.filter(node => { const css = getComputedStyle(node); return css.opacity !== '0' && css.clipPath !== 'inset(50%)' && css.clip !== 'rect(0px, 0px, 0px, 0px)'; }).map(node => node.outerHTML))
  assert.deepEqual(nativeControls, [], 'Only hidden accessibility inputs may remain inside Base UI controls')
  report.checks.push('390px: long select keyboard End, collision bounds, color popover, segmented navigation, no visible browser-native composite controls')
  assert.deepEqual(report.errors, [])
  console.log(JSON.stringify(report, null, 2))
} finally {
  await browser.close()
  await writeFile(`${output}/report.json`, JSON.stringify(report, null, 2))
}
